---
title: "README"
author: "Calen P. Ryan and Milan Hilde-Jones"
date: "6/30/2021"
output: html_document
---

Use this document for metadata about the project. This could include:  

* Clarity: Notes about analysis decisions  
* Reproducibility: Details for someone else picking up the analysis (or future you)  
* Something else (feel free to add)  
 
The document uses Rmarkdown. You can find out more about how to write using this language [in this cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf).

# Setup

This project is going to require growth data from a number of years during childhood, as well as epigenetic age data during young adulthood (20-22 years old) for about 500 individuals. (We have more data coming, but this is going to lay the foundation for the larger analysis). 

Data about growth can be accessed at the [UNC Dataverse](https://dataverse.unc.edu/dataverse/cebu)


### We're going to need: 

* Only live births (OUTCOME)
* Date of Birth (for age) (YEARBIRT, MNTHBRTH, DAYBIRTH)
* Sex of child (SEXCHILD)
* Birth weight, length, skinfolds if we have them  
* Date of weighing/measuring (used to calculate ages at measuring) 



#### Live births (OUTCOME):  

 1 - Single live birth  
 2 - Single stillbirth    (Code -9 from STATUSBB to DAYFEDLS;  
     from HOLDBABY to SKINFLD3)  
 3 - Miscarriage/abortion (Code -9 from SEXCHILD to SKINFLD3)   
 4 - Twin birth, regardless whether alive or dead  
     (Code -9 from MNTHBRTH to SKINFLD3)  
 5 - Multiple births i.e. triplets (Code -9 from MNTHBRTH to SKINFLD3)  
-8 - NR/DK  


#### Date of Birth:  
DAYBIRTH: DAY OF MONTH THAT SINGLE LIVE BIRTH/MISCARRIAGE/STILLBIRTH OCCURRED
MNTHBRTH: MONTH THAT SINGLE LIVE BIRTH/MISCARRIAGE/STILLBIRTH OCCURRED
YEARBIRT: YEAR SINGLE LIVE BIRTH/MISCARRIAGE/STILLBIRTH OCCURRED



#### Sex of child ((SEXCHILD)):

 1 - Male  
 2 - Female  
-8 - NR/DK  
-9 - NA  


#### For birth weight, we need:  

BBWIEGHT: WAS THE INFANT WEIGHED AFTER DELIVERY?  
 0 - No, baby has not been weighed yet (Code -9 in WEIGHT1)  
 1 - Yes, first hour of life  
 2 - Yes, later on first day of life  
 3 - Yes, second day of life  
 4 - Yes, third day of life  
 5 - Yes, fourth day of life  
 6 - Yes, fifth day of life  
 7 - Yes, after fifth day of life  
-8 - NR/DK  
-9 - NA  

If yes (>0),   
- then use WEIGHT1, corrected for age (using BBWIEGHT or HRSAFTER coding for age)    

If not (<1),  
- WEIGHTAK: WEIGHT IN GRAMS OF THE INFANT WHEN WEIGHED BY THE INTERVIEWER, corrected for age (YEARINTW, MOTHINTW, DAYINTW)  

**Weight needs to have been measured <2 weeks (30 days?) since birth, or the values will be all out of whack. **

**What is the difference between WEIGHTAK: WEIGHT IN GRAMS OF THE INFANT WHEN WEIGHED BY THE INTERVIEWER and WEIGHTGM INFANT'S WEIGHT IN GRAMS AT THE TIME OF WEIGHING**


#### HEIGHTCM



